# -*- coding: utf-8 -*-
"""stage_0_Prem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCb5DOALVoyp8LgVWDDEML4V1hTwB3Aa
"""

Name = "Prem Thapa"
Slack_username = "@Prem"
gmail = "premthapa2580@gmail.com"
biostack = "Drug Discovery"

print("Hello My Name is {} and you can find me on slack by searching for {}  or mail me at {}, My biostack is {}".format(Name , Slack_username,gmail,biostack))